"""Structural comparison: old 4-pass vs new 2-stage pipeline.

This module provides a static comparison of the two architectures
WITHOUT running them through an LLM. It compares:

1. Request volume (LLM calls per clause)
2. Coverage model (which clauses are examined)
3. Theme generation approach
4. Noise filtering mechanisms

A full execution-based comparison would require LLM calls for both
pipelines on the same contract. This is deferred to integration testing.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class PipelineProfile:
    """Structural profile of a pipeline architecture."""
    name: str
    llm_calls_per_clause: str  # Description of call pattern
    coverage_model: str
    noise_filtering: str
    theme_generation: str
    deep_check_model: str
    estimated_calls_for_n_clauses: str  # Formula


OLD_PIPELINE = PipelineProfile(
    name="4-Pass Pipeline (v1)",
    llm_calls_per_clause="4× per clause (breit + perspektive + implizit + bankregulatorik)",
    coverage_model="Every clause read 4 times by 4 different prompts",
    noise_filtering=(
        "Post-hoc: dedup removes duplicates after all 4 passes complete. "
        "No early filtering — all clauses go through all 4 passes regardless of content."
    ),
    theme_generation=(
        "Clustering operates on all raw findings from 4 passes. "
        "Theme titles generated by LLM with anti-generic rules. "
        "But input contains noise from all passes → themes can collapse into buckets."
    ),
    deep_check_model="None — all analysis happens in the 4 fixed passes.",
    estimated_calls_for_n_clauses="4×N (always)",
)

NEW_PIPELINE = PipelineProfile(
    name="2-Stage Pipeline (v2)",
    llm_calls_per_clause="1× for risk screen + 0-K for deep checks (K = triggered domains)",
    coverage_model=(
        "Every clause read exactly once in risk screen. "
        "Non-problematic clauses dropped immediately. "
        "Only flagged clauses routed to domain-specific deep checks."
    ),
    noise_filtering=(
        "Hard filter after first read: is_problematic=false → dropped. "
        "Anti-noise rules embedded in risk_screen prompt. "
        "No further LLM calls for non-problematic clauses."
    ),
    theme_generation=(
        "Clustering operates on pre-filtered, problem-oriented findings. "
        "Input already contains only confirmed problems → themes more specific. "
        "Same anti-generic title rules apply."
    ),
    deep_check_model=(
        "Trigger-based: each flagged clause routes to 0-K domain-specific prompts. "
        "Typical K=1-2. Max K=10 (all domains). "
        "Deep checks add: negotiation points, alternative wording, bidder questions."
    ),
    estimated_calls_for_n_clauses="N + Σ(K_i for flagged clauses). Typically N + 0.3×N = 1.3×N",
)


@dataclass
class ComparisonResult:
    """Side-by-side comparison of two pipeline architectures."""
    dimension: str
    old_value: str
    new_value: str
    verdict: str  # IMPROVED | SAME | REGRESSED | TRADEOFF


def compare_architectures() -> list[ComparisonResult]:
    """Generate structural comparison between old and new pipeline."""
    return [
        ComparisonResult(
            dimension="LLM calls per clause",
            old_value="4 (fixed)",
            new_value="1 + K (K=0 for non-problematic, K=1-2 for flagged)",
            verdict="IMPROVED — ~70% fewer calls for typical contracts",
        ),
        ComparisonResult(
            dimension="Noise filtering",
            old_value="Post-hoc dedup only (no early filtering)",
            new_value="Hard filter after first read (is_problematic=false → dropped)",
            verdict="IMPROVED — non-problematic clauses never reach deep analysis",
        ),
        ComparisonResult(
            dimension="Theme input quality",
            old_value="All raw findings from 4 passes (includes noise)",
            new_value="Only confirmed problems with structured problem_types",
            verdict="IMPROVED — cleaner input → more specific themes",
        ),
        ComparisonResult(
            dimension="Problem type taxonomy",
            old_value="Free-text categories (LLM-generated, inconsistent)",
            new_value="17 normalized problem_types with defined semantics",
            verdict="IMPROVED — deterministic classification → consistent routing",
        ),
        ComparisonResult(
            dimension="Deep analysis depth",
            old_value="4 generic passes per clause (breadth over depth)",
            new_value="Domain-specific deep checks with tailored prompts",
            verdict="IMPROVED — deeper analysis where it matters",
        ),
        ComparisonResult(
            dimension="Negotiation output",
            old_value="Generated in editorial pass only",
            new_value="Generated in deep checks + refined in editorial",
            verdict="IMPROVED — domain-specific negotiation points from deep checks",
        ),
        ComparisonResult(
            dimension="Recall risk",
            old_value="High recall (4 passes = 4 chances to catch)",
            new_value="Single-read risk: if first read misses, clause is dropped",
            verdict="TRADEOFF — recall depends entirely on risk_screen quality",
        ),
        ComparisonResult(
            dimension="Cost scaling",
            old_value="Linear: 4×N always",
            new_value="Sub-linear: N + ~0.3×N for typical contracts",
            verdict="IMPROVED — significant cost reduction",
        ),
    ]


def format_comparison_text() -> str:
    """Format the comparison as human-readable text."""
    results = compare_architectures()
    lines = []
    lines.append("=" * 80)
    lines.append("PIPELINE ARCHITECTURE COMPARISON: Old (4-pass) vs New (2-stage)")
    lines.append("=" * 80)
    lines.append("")

    for r in results:
        lines.append(f"--- {r.dimension} ---")
        lines.append(f"  Old: {r.old_value}")
        lines.append(f"  New: {r.new_value}")
        lines.append(f"  → {r.verdict}")
        lines.append("")

    lines.append("=" * 80)
    lines.append("KNOWN TRADEOFFS")
    lines.append("=" * 80)
    lines.append("")
    lines.append("1. RECALL RISK: The new pipeline reads each clause only once.")
    lines.append("   If the risk_screen prompt misses a subtle problem,")
    lines.append("   there is no second-chance pass to catch it.")
    lines.append("   Mitigation: golden testset validation + recall monitoring.")
    lines.append("")
    lines.append("2. PROMPT SENSITIVITY: The new pipeline depends heavily on")
    lines.append("   the quality of a single risk_screen prompt.")
    lines.append("   The old pipeline had 4 different prompts with different angles.")
    lines.append("   Mitigation: the risk_screen prompt is comprehensive and")
    lines.append("   includes explicit examples + anti-noise rules.")
    lines.append("")
    lines.append("3. DEEP CHECK ROUTING: If trigger_domains are mis-assigned,")
    lines.append("   deep checks may analyze the wrong domain for a clause.")
    lines.append("   Mitigation: trigger_domain_coverage tracking in validation.")
    lines.append("")

    return "\n".join(lines)
