"""Early semantic deduplication for cross-pass raw findings.

Runs BEFORE consolidation to remove duplicate findings generated by
multiple discovery passes analyzing the same paragraphs. Operates
purely on RawFinding objects — does not touch the database.

Dedup criteria:
- Same paragraph / segment id
- Same or closely related risk category
- High description similarity (> 0.85)

Additionally enforces a per-paragraph limit of 2 findings max.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from dataclasses import dataclass
from difflib import SequenceMatcher

from app.discovery.passes.base import RawFinding

logger = logging.getLogger(__name__)

# Severity ordering for tie-breaking
_RISK_ORDER = {"Kritisch": 4, "Hoch": 3, "Mittel": 2, "Niedrig": 1, "Hinweis": 0}

# Similarity threshold for description comparison
_DESC_SIMILARITY_THRESHOLD = 0.85

# Maximum findings to keep per paragraph/segment
MAX_FINDINGS_PER_PARAGRAPH = 2


@dataclass
class DedupResult:
    """Result of the early deduplication stage."""
    findings: list[RawFinding]
    raw_before: int
    raw_after: int
    duplicates_removed: int


def _similarity(a: str, b: str) -> float:
    """Compute normalized text similarity between two strings."""
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, a.lower().strip(), b.lower().strip()).ratio()


def _finding_sort_key(f: RawFinding) -> tuple:
    """Sort key: higher severity first, longer description first, earlier pass first."""
    # Pass ordering: earlier passes get lower numbers (preferred)
    pass_order = 0
    qp = f.quelle_pass.lower()
    if "breit" in qp:
        pass_order = 0
    elif "perspektive" in qp or "perspektivische" in qp:
        pass_order = 1
    elif "implizit" in qp:
        pass_order = 2
    elif "bank" in qp or "regulatorik" in qp:
        pass_order = 3
    else:
        pass_order = 4

    return (
        -_RISK_ORDER.get(f.risikostufe, 0),  # higher severity first
        -len(f.erklaerung or f.kurzbeschreibung),  # longer description first
        pass_order,  # earlier pass first
    )


def _normalize_category(cat: str) -> str:
    """Normalize category for comparison (lowercase, strip whitespace)."""
    return cat.strip().lower() if cat else ""


def deduplicate_raw_findings(findings: list[RawFinding]) -> DedupResult:
    """Remove semantic duplicates across discovery passes.

    1. Group findings by segment_id
    2. Within each group, find duplicates (same category + similar description)
    3. Keep the best finding from each duplicate cluster
    4. Enforce per-paragraph limit of MAX_FINDINGS_PER_PARAGRAPH
    """
    raw_before = len(findings)

    if not findings:
        return DedupResult(findings=[], raw_before=0, raw_after=0, duplicates_removed=0)

    # Group by first segment_id (primary paragraph identifier)
    by_segment: dict[str, list[RawFinding]] = defaultdict(list)
    no_segment: list[RawFinding] = []

    for f in findings:
        if f.segment_ids:
            # Use first segment_id as the grouping key
            by_segment[f.segment_ids[0]].append(f)
        else:
            no_segment.append(f)

    deduplicated: list[RawFinding] = []

    for seg_id, group in by_segment.items():
        if len(group) <= 1:
            deduplicated.extend(group)
            continue

        # Sort by quality (best first)
        group.sort(key=_finding_sort_key)

        # Greedy dedup within segment group
        kept: list[RawFinding] = []
        for candidate in group:
            is_dup = False
            cand_cat = _normalize_category(candidate.kategorie)

            for existing in kept:
                exist_cat = _normalize_category(existing.kategorie)

                # Same or similar category?
                cats_match = (cand_cat == exist_cat
                              or _similarity(cand_cat, exist_cat) > 0.7)
                if not cats_match:
                    continue

                # Similar description?
                desc_a = candidate.erklaerung or candidate.kurzbeschreibung
                desc_b = existing.erklaerung or existing.kurzbeschreibung
                desc_sim = _similarity(desc_a, desc_b)

                if desc_sim > _DESC_SIMILARITY_THRESHOLD:
                    is_dup = True
                    logger.debug(
                        f"Dedup: '{candidate.kurzbeschreibung[:60]}' "
                        f"({candidate.quelle_pass}) is duplicate of "
                        f"'{existing.kurzbeschreibung[:60]}' "
                        f"({existing.quelle_pass}) — "
                        f"desc_sim={desc_sim:.2f}, cat='{cand_cat}'"
                    )
                    break

            if not is_dup:
                kept.append(candidate)

        # Enforce per-paragraph limit
        if len(kept) > MAX_FINDINGS_PER_PARAGRAPH:
            # Already sorted by quality — just truncate
            removed = len(kept) - MAX_FINDINGS_PER_PARAGRAPH
            logger.debug(
                f"Dedup: Segment {seg_id} had {len(kept)} findings after dedup, "
                f"truncated to {MAX_FINDINGS_PER_PARAGRAPH} (removed {removed})"
            )
            kept = kept[:MAX_FINDINGS_PER_PARAGRAPH]

        deduplicated.extend(kept)

    # Add findings without segment IDs (pass through)
    deduplicated.extend(no_segment)

    raw_after = len(deduplicated)
    duplicates_removed = raw_before - raw_after

    logger.info(
        f"Early dedup: {raw_before} -> {raw_after} findings "
        f"({duplicates_removed} duplicates removed)"
    )

    return DedupResult(
        findings=deduplicated,
        raw_before=raw_before,
        raw_after=raw_after,
        duplicates_removed=duplicates_removed,
    )
